version: 2
jobs:
  build-ubuntu1804:
    docker:
      - image: sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests
    
    working_directory: ~/build-4-linux
    
    steps:
    - checkout
    - run:
        name: Configure
        command: ./configure Release --config-tag Unix --apply-default-release-flags
    - run:
        name: build
        command: make all -j3
    - store_artifacts:
       path: ~/build-4-linux/Builds/Debug


workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ubuntu1804
