version: 2.1
commands:
  build-4-unix:
    parameters:
      configName:
        type: string
      configureArgs:
        type: string

    steps:
      - checkout
      - run:
          name: Update SubModules
          command: git submodule update --init --recursive
      - run:
          name: Configure
          command: |
            cd ThirdPartyComponents/Stroika/StroikaRoot
            ./ScriptsLib/MakeBuildRoot ../../../
            ./configure << parameters.configName >> << parameters.configureArgs >>
      - run:
          name: Build
          command: |
            make all -j2
            (cd ~/build-4-linux/Builds/<< parameters.configName >>/WhyTheFuckIsMyNetworkSoSlow/ && mkdir Artifacts && cp *.deb Artifacts/)
      - store_artifacts:
          path: ~/build-4-linux/Builds/<< parameters.configName >>/WhyTheFuckIsMyNetworkSoSlow/Artifacts
          destination: WhyTheFuckIsMyNetworkSoSlow

jobs:
  build-ubuntu1804:
    docker:
      - image: sophistsolutionsinc/whythefuckismynetworksoslow-ubuntu-1804

    working_directory: ~/build-4-linux

    steps:
      - build-4-unix:
          configName: Release
          configureArgs: --apply-default-release-flags --compiler-driver g++-8

  build-raspberrypi:
    docker:
      - image: sophistsolutionsinc/whythefuckismynetworksoslow-ubuntu-1804

    working_directory: ~/build-4-linux

    steps:
      - build-4-unix:
          configName: raspberrypi-release
          configureArgs: --apply-default-release-flags --compiler-driver 'arm-linux-gnueabihf-g++-8' --cross-compiling true;

  build-macos:
    macos:
      xcode: "11.3"

    working_directory: ~/build-4-linux

    steps:
      - build-4-unix:
          configName: Release
          configureArgs: --config-tag Unix --apply-default-release-flags

  build-windows:
    executor: win/default

    steps:
      - checkout
      - run:
          name: Update SubModules
          command: git submodule update --init --recursive
      - run:
          name: Configure
          command: |
            cd ThirdPartyComponents/Stroika/StroikaRoot
            ./ScriptsLib/MakeBuildRoot ../../../
            ./configure Release --config-tag Unix --apply-default-release-flags

workflows:
  version: 2
  build:
    jobs:
      - build-ubuntu1804:
          filters:
            branches:
              only:
                # - v1-Dev
                - v1-Release
      - build-raspberrypi:
          filters:
            branches:
              only:
                # - v1-Dev
                - v1-Release
      # Not supported on free build plan
      #- build-macos
      # For now this doesn't appear to work
      #- build-windows
