version: 2.1
jobs:
  build-4-unix:
    parameters:
      dockerImage:
        type: string
      configName:
        type: string
      configureArgs:
        type: string

    docker:
      - image: << parameters.dockerImage >>
    
    working_directory: ~/build-4-linux
    
    steps:
    - checkout
    - run:
        name: update submdoules
        command: git submodule update --init --recursive
    - run:
        name: Configure
        command: |
          cd ThirdPartyComponents/Stroika/StroikaRoot
          ./ScriptsLib/MakeBuildRoot ../../../
          ./configure << parameters.configName >> << parameters.configureArgs >>
    - run:
        name: build
        command: make all -j2
    - store_artifacts:
       path: ~/build-4-linux/Builds/<< parameters.configName >>/WhyTheFuckIsMyNetworkSoSlow
       destination: WhyTheFuckIsMyNetworkSoSlow

  build-ubuntu1804:
    docker:
      - image: sophistsolutionsinc/whythefuckismynetworksoslow-debian-small
    
    working_directory: ~/build-4-linux
    
    steps:
    - build-4-unix:
          dockerImage: dockerImage
          configName: Release
          configureArgs: --config-tag Unix --apply-default-release-flags

  build-raspberrypi:
    docker:
      - image: sophistsolutionsinc/whythefuckismynetworksoslow-debian-crosscompile-raspberrypi
    
    working_directory: ~/build-4-linux
    
    steps:
    - build-4-unix:
          dockerImage: dockerImage
          configName: raspberrypi-release
          configureArgs: --config-tag Unix --config-tag raspberrypi --apply-default-release-flags --only-if-has-compiler --compiler-driver 'arm-linux-gnueabihf-g++-7' --cross-compiling true;


workflows:
  version: 2
  build:
    jobs:
      - build-ubuntu1804
      - build-raspberrypi
