version: 2
jobs:
  build-ubuntu1804:
    docker:
      - image: sophistsolutionsinc/whythefuckismynetworksoslow-debian-small
    
    working_directory: ~/build-4-linux
    
    steps:
    - checkout
    - run:
        name: update submdoules
        command: git submodule update --init --recursive
    - run:
        name: Configure
        command: |
          cd ThirdPartyComponents/Stroika/StroikaRoot
          ./ScriptsLib/MakeBuildRoot ../../../
          ./configure Release --config-tag Unix --apply-default-release-flags
    - run:
        name: build
        command: make all -j2
    - store_artifacts:
       path: ~/build-4-linux/Builds/Release/WhyTheFuckIsMyNetworkSoSlow
       destination: WhyTheFuckIsMyNetworkSoSlow

  build-raspberrypi:
    docker:
      - image: sophistsolutionsinc/whythefuckismynetworksoslow-debian-crosscompile-raspberrypi
    
    working_directory: ~/build-4-linux
    
    steps:
    - checkout
    - run:
        name: update submdoules
        command: git submodule update --init --recursive
    - run:
        name: Configure
        command: |
          cd ThirdPartyComponents/Stroika/StroikaRoot
          ./ScriptsLib/MakeBuildRoot ../../../
          ./configure raspberrypi-release --config-tag Unix --config-tag raspberrypi --apply-default-release-flags --only-if-has-compiler --compiler-driver 'arm-linux-gnueabihf-g++-7' --cross-compiling true);\
    - run:
        name: build
        command: make all -j2
    - store_artifacts:
       path: ~/build-4-linux/Builds/raspberrypi-release/WhyTheFuckIsMyNetworkSoSlow
       destination: WhyTheFuckIsMyNetworkSoSlow


workflows:
  version: 2
  build:
    jobs:
      - build-ubuntu1804
      - build-raspberrypi
