# escape=`

FROM sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19

CMD ["cmd", "/c", "call FixupPath.bat && echo see Getting-Started-With-Stroika.md && cmd"]

### NOTE TO RUN
###     docker run -v c:\Sandbox:c:\Sandbox -it sophistsolutionsinc/ka-buildvm-windows-cygwin-vs2k19:latest
###     docker run -it sophistsolutionsinc/ka-buildvm-windows-cygwin-vs2k19:latest
