all:
	###quick hack impl - make links and then cd there and make
	mkdir -p ../IntermediateFiles/$(CONFIGURATION)/WhyTheFuckIsMyNetworkSoSlow
	ln -s Projects/Unix/Makefile ../IntermediateFiles/$(CONFIGURATION)/WhyTheFuckIsMyNetworkSoSlow/Makefile
	$(MAKE) --directory WhyTheFuckIsMyNetworkSoSlow all