export TOP_ROOT=$(shell realpath ../)/

all:
	@$(MAKE) --directory=Stroika --no-print-directory all CONFIGURATION=$(CONFIGURATION)

clean:
	@$(MAKE) --directory=Stroika --no-print-directory clean  CONFIGURATION=$(CONFIGURATION)

clobber:
	@$(MAKE) --directory=Stroika --no-print-directory clobber CONFIGURATION=$(CONFIGURATION)
